---
version: "3.0"
services:
  test:
    image: "markteetsdev/sudoku-dev"
    container_name: "sudoku-test"
    # won't need ports until later
    # ports:
    #   - 3000:3000
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: "npm run test"
volumes:
  node_modules:
